# Generated by Django 3.0.6 on 2020-11-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='amtrecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_desc', models.CharField(max_length=250)),
                ('contractor', models.CharField(max_length=50)),
                ('listing_no', models.CharField(max_length=50)),
                ('amt_date', models.DateField(blank=True, null=True)),
                ('contract_value', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=10)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amt_app.Currency')),
            ],
        ),
    ]
