# Generated by Django 3.0.6 on 2020-10-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lporecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_desc', models.CharField(max_length=250)),
                ('order_to', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=100)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('order_value', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=10)),
                ('currency', models.CharField(blank=True, choices=[('Naira', 'Naira'), ('Dollars', 'Dollars')], max_length=10, null=True)),
            ],
        ),
    ]
