# Generated by Django 3.0.6 on 2020-11-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lporecords',
            name='order_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lporecords',
            name='order_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lporecords',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lpo_app.Currency'),
        ),
    ]
