# Generated by Django 3.0.6 on 2020-11-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpo_app', '0002_auto_20201103_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lporecords',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lpo_app.Currency'),
        ),
    ]
